plugins:
- serverless-offline

service: twitter-scraping

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

functions:
  scrapeTweets:
    handler: src/writeTweetsToDynamo.handler
    method: get
    events:
    - schedule: rate(2 hours)

  getTweets:
    handler: src/api/getTweets.handler
    method: get
    events:
    - http:
        path: tweets
        method: get
